name: sprout_journal
description: "Gartenapp im Fach DAPI SoSe 24"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.3.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  logger: ^2.2.0
  sqflite: any
  path_provider: ^2.0.8
  path: ^1.9.0  
  intl: ^0.19.0
  image_picker: ^1.1.1
  flutter_image_compress: ^2.3.0
  image: any
  flutter_dotenv: ^5.0.2 
  provider: ^6.1.1
  firebase_core: ^2.24.2
  cloud_firestore: ^4.14.0
  firebase_auth: ^4.17.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/plants.json
    - assets/images/standard_plant.png
    - assets/images/plants/
    - .env

flutter_launcher_icons:
  android : "launcher_icon" 
  ios: true
  image_path: "assets/icon/icon.png"
  adaptive_icon_foreground: "assets/icon/icon.png"
  adaptive_icon_background: "#ffffff"
