name: sprout_journal
description: "Gartenapp im Fach DAPI SoSe 24"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.3.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  logger: ^2.2.0
  sqflite: any
  path_provider: ^2.0.8
  path: ^1.9.0  
  intl: ^0.17.0
  image_picker: ^0.8.4+8
  flutter_cache_manager: ^3.3.0
  image: any

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/plants.json
    - assets/images/standard_plant.png
    - assets/images/plants/

flutter_launcher_icons:
  android : "launcher_icon" 
  ios: true
  image_path: "assets/icon/icon.png"
  adaptive_icon_foreground: "assets/icon/icon.png"
  adaptive_icon_background: "#ffffff"
